name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Permisos necesarios para el deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Configuración para GitHub Pages
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install -g http-server
        
    - name: Test build
      run: |
        echo "Testing application structure..."
        ls -la
        echo "Checking for required files..."
        test -f manifest.json && echo "✅ manifest.json found"
        test -f sw.js && echo "✅ sw.js found"
        test -f dashboard.html && echo "✅ dashboard.html found"
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 